/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bengreenier_blackhole_natives_WinRegistry */

#ifndef _Included_com_bengreenier_blackhole_natives_WinRegistry
#define _Included_com_bengreenier_blackhole_natives_WinRegistry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bengreenier_blackhole_natives_WinRegistry
 * Method:    writeKey
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bengreenier_blackhole_natives_WinRegistry_writeKey
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_bengreenier_blackhole_natives_WinRegistry
 * Method:    writeValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bengreenier_blackhole_natives_WinRegistry_writeValue
  (JNIEnv *, jclass, jint, jstring, jstring, jint);

/*
 * Class:     com_bengreenier_blackhole_natives_WinRegistry
 * Method:    getValue
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bengreenier_blackhole_natives_WinRegistry_getValue
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
