/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bengreenier_blackhole_natives_WinRegistry_Keys */

#ifndef _Included_com_bengreenier_blackhole_natives_WinRegistry_Keys
#define _Included_com_bengreenier_blackhole_natives_WinRegistry_Keys
#ifdef __cplusplus
extern "C" {
#endif
#undef com_bengreenier_blackhole_natives_WinRegistry_Keys_HKEY_CLASSES_ROOT
#define com_bengreenier_blackhole_natives_WinRegistry_Keys_HKEY_CLASSES_ROOT 1L
#undef com_bengreenier_blackhole_natives_WinRegistry_Keys_HKEY_CURRENT_CONFIG
#define com_bengreenier_blackhole_natives_WinRegistry_Keys_HKEY_CURRENT_CONFIG 2L
#undef com_bengreenier_blackhole_natives_WinRegistry_Keys_HKEY_CURRENT_USER
#define com_bengreenier_blackhole_natives_WinRegistry_Keys_HKEY_CURRENT_USER 3L
#undef com_bengreenier_blackhole_natives_WinRegistry_Keys_HKEY_LOCAL_MACHINE
#define com_bengreenier_blackhole_natives_WinRegistry_Keys_HKEY_LOCAL_MACHINE 4L
#undef com_bengreenier_blackhole_natives_WinRegistry_Keys_HKEY_USERS
#define com_bengreenier_blackhole_natives_WinRegistry_Keys_HKEY_USERS 5L
#ifdef __cplusplus
}
#endif
#endif
