/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bengreenier_blackhole_natives_WinRegistry_Types */

#ifndef _Included_com_bengreenier_blackhole_natives_WinRegistry_Types
#define _Included_com_bengreenier_blackhole_natives_WinRegistry_Types
#ifdef __cplusplus
extern "C" {
#endif
#undef com_bengreenier_blackhole_natives_WinRegistry_Types_DWORD
#define com_bengreenier_blackhole_natives_WinRegistry_Types_DWORD 1L
#undef com_bengreenier_blackhole_natives_WinRegistry_Types_QWORD
#define com_bengreenier_blackhole_natives_WinRegistry_Types_QWORD 2L
#undef com_bengreenier_blackhole_natives_WinRegistry_Types_STRING
#define com_bengreenier_blackhole_natives_WinRegistry_Types_STRING 3L
#undef com_bengreenier_blackhole_natives_WinRegistry_Types_BINARY
#define com_bengreenier_blackhole_natives_WinRegistry_Types_BINARY 4L
#undef com_bengreenier_blackhole_natives_WinRegistry_Types_MULTISTRING
#define com_bengreenier_blackhole_natives_WinRegistry_Types_MULTISTRING 5L
#undef com_bengreenier_blackhole_natives_WinRegistry_Types_EXPANDABLESTRING
#define com_bengreenier_blackhole_natives_WinRegistry_Types_EXPANDABLESTRING 6L
#ifdef __cplusplus
}
#endif
#endif
